on:
  push:
    paths: ['**.qmd']
  workflow_dispatch:

name: render-manuscript

jobs:
  render-quarto:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("osfr", "tidyverse", "jsonlite", "edfReader", "fuzzyjoin", "ravetools", "eegkit", "gee"))'

      - name: Download OSF data
        run: |
          Rscript preprocessing/download-raw-data-from-osf.R

      - name: Preprocess data
        run: |
          Rscript preprocessing/run-preprocessing_local_machine.R
          Rscript preprocessing/merge-local.R
          Rscript preprocessing/merge-behavioral-local.R
          
